apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: | 
    <html>
    <head><title>NGINX + PVC</title></head>
    <body>
      <h1>Hello from Persistent Volume!</h1>
    </body>
    </html>
