apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  initContainers:
    - name: init-copy
      image: busybox
      command: ['sh', '-c', 'cp /tmp/index.html/index.html /usr/share/nginx/html/index.html']
      volumeMounts:
        - name: nginx-storage
          mountPath: /usr/share/nginx/html
        - name: html
          mountPath: /tmp/index.html
  containers:
    - name: nginx
      image: nginx:1.21
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: nginx-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-storage
      persistentVolumeClaim:
        claimName: nginx-pvc
    - name: html
      configMap:
        name: nginx-html

